apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sql-jpa
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sql-jpa
spec:
  source:
    git:
      url: https://github.com/dforbes-pivotal/spring-sql-jpa.git
      ref:
        branch: master
